// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StandBy.Data.Context;

namespace StandBy.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221201014516_SQLSERVER")]
    partial class SQLSERVER
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StandBy.Business.Models.Cliente", b =>
                {
                    b.Property<int>("CLIENTE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CAPITAL")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DECIMAL(18,2)");

                    b.Property<string>("CLASSIFICACAO")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DATE");

                    b.Property<DateTime>("DATA_FUNDACAO")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_FUNDACAO");

                    b.Property<bool>("QUARENTENA")
                        .HasColumnType("bit")
                        .HasColumnName("QUARENTENA");

                    b.Property<string>("RAZAO_SOCIAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("varchar(60)");

                    b.Property<bool>("STATUS_CLIENTE")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS_CLIENTE");

                    b.HasKey("CLIENTE_ID");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
