// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StandBy.Data.Context;

namespace StandBy.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("StandBy.Business.Models.Cliente", b =>
                {
                    b.Property<int>("CLIENTE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CAPITAL")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CLASSIFICACAO")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DATA_FUNDACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("QUARENTENA")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RAZAO_SOCIAL")
                        .HasColumnType("longtext");

                    b.Property<bool>("STATUS_CLIENTE")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CLIENTE_ID");

                    b.ToTable("cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
